# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staged Build on Droplet

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: /home/dbs/dbs-app/staged/dbs-admin-panel/

jobs:
  staged-build:

    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
